[package]
name = "rust-v7-cmd"
version = "0.1.0"
authors = ["James Bostock <james.bostock@gmail.com>"]
description = "Support library for the rust-v7-cmd crate."
repository = "https://github.com/james-bostock/rust-v7-cmd"
readme = "README.md"
license = "MIT"
edition = "2018"
